spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: non_null
  datasource:
    name: fiji
    url: jdbc:mysql://127.0.0.1:3306/xiaomianshi?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 3013689
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
#    database: 0
#    pool:
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#      max-active: 8
#    timeout: 0
mybatis:
  type-aliases-package: com.xiaomianshi.model
#  type-handlers-package: com.xiaomianshi.core.dao.typehandler
  mapper-locations: classpath:mapper/*.xml
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
logging:
  config: classpath:config/log/logback-spring.xml
server:
  port: 8888
#  servlet:
#    session:
#      timeout:

#

#favorites.base.path=http://127.0.0.1:8080/
#forgotpassword.url=http://127.0.0.1:8080/newPassword

######   file path  begin ######
#static.url=E:\\temp\\
#file.profilepictures.url=profilepictures/
#file.backgroundpictures.url=backgroundpictures/
######   file path end ######