debug: true
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev

#static.url = /usr/local/static
#file.profilepictures.url = file/profilepictures/
#file.backgroundpictures.url = file/backgroundpictures/


com:
  xiaomianshi:
    web:
      name: 小面试
#      copywright: @2017 - 2018 ${com.didispace.blog.name}